### ISSUE TITLE
Serialize breaks with: TypeError: Cannot read property 'mayDeepCopy' of undefined

### ISSUE THREAD

**Issue by Judahh** [terrymorse58/serialize-anything#2]
When objectBehaviors[o] is undefined, serialize breaks at: 
`if (!objectBehaviors[o].mayDeepCopy)`

**Comment by terrymorse58** [comment]
Thanks for the report. There was a bug in `deep-copy-all` version < 1.3.3 that was causing objectBehaviors[] to be undefined.

I have pushed `serialize-anything` version 1.1.7, which uses `deep-copy-all` version 1.3.3.

The test suite now shows no errors.

**Comment by Judahh** [comment]
Looks like the package is missing:
Error: Cannot find module './node_modules/deep-copy-all/index.js'
Require stack:
- /Users/judah/auth/node_modules/serialize-anything/index.js
- /Users/judah/auth/next.config.ts
- /Users/judah/auth/next.config.js
- /Users/judah/auth/node_modules/next/dist/next-server/server/config.js
- /Users/judah/auth/node_modules/next/dist/next-server/server/next-server.js
- /Users/judah/auth/node_modules/next/dist/server/next.js
- /Users/judah/auth/node_modules/next/dist/server/lib/start-server.js
- /Users/judah/auth/node_modules/next/dist/cli/next-dev.js
- /Users/judah/auth/node_modules/next/dist/bin/next
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:892:15)
    at Function.Module._load (internal/modules/cjs/loader.js:742:27)
    at Module.require (internal/modules/cjs/loader.js:964:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/judah/auth/node_modules/serialize-anything/index.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:1075:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:1096:10)
    at Object.require.extensions.<computed> [as .js] (/Users/judah/auth/node_modules/ts-node/src/index.ts:1045:43)
    at Module.load (internal/modules/cjs/loader.js:940:32)
    at Function.Module._load (internal/modules/cjs/loader.js:781:14)
    at Module.require (internal/modules/cjs/loader.js:964:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/judah/auth/next.config.ts:7:1)
    at Module._compile (internal/modules/cjs/loader.js:1075:30)
    at Module.m._compile (/Users/judah/auth/node_modules/ts-node/src/index.ts:1056:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1096:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/judah/auth/node_modules/ts-node/src/index.ts:1059:12)
    at Module.load (internal/modules/cjs/loader.js:940:32)
    at Function.Module._load (internal/modules/cjs/loader.js:781:14)
    at Module.require (internal/modules/cjs/loader.js:964:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/judah/auth/next.config.js:3:18) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/judah/auth/node_modules/serialize-anything/index.js',
    '/Users/judah/auth/next.config.ts',
    '/Users/judah/auth/next.config.js',
    '/Users/judah/auth/node_modules/next/dist/next-server/server/config.js',
    '/Users/judah/auth/node_modules/next/dist/next-server/server/next-server.js',
    '/Users/judah/auth/node_modules/next/dist/server/next.js',
    '/Users/judah/auth/node_modules/next/dist/server/lib/start-server.js',
    '/Users/judah/auth/node_modules/next/dist/cli/next-dev.js',
    '/Users/judah/auth/node_modules/next/dist/bin/next'
  ]
}

**Comment by terrymorse58** [comment]
Did you run these commands:

```
cd serialize-anything
npm install
```

That will install `deep-copy-all` into the serialize-anything/node_modules folder.

**Comment by Judahh** [comment]
It's already in my package. I just updated serialize-anything, deleted yarn.lock and run yarn. Didn't work. I've tried deleting node_modules and didn't work either.

**Comment by terrymorse58** [comment]
Try a clean re-install. I just did the following, and it worked with no problem.
```
git clone https://github.com/terrymorse58/serialize-anything.git
cd serialize-anything
npm install
npm run test
```

**Comment by Judahh** [comment]
> Try a clean re-install. I just did the following, and it worked with no problem.
> 
> ```
> git clone https://github.com/terrymorse58/serialize-anything.git
> cd serialize-anything
> npm install
> npm run test
> ```

In this case you're not using as a module.
Anyways I've found the problem. You're importing the package using "./node_modules/deep-copy-all/index.js" instead of "deep-copy-all". So if the package is used by another it will not find it.

**Comment by terrymorse58** [comment]
Thanks for finding that, I've pushed a revision with this change:
```javascript
const deepCopy = require('deep-copy-all');
```

**Comment by Judahh** [comment]
Ok, now it's working but I'm receiving: `Error max depth of 20 levels exceeded, possible circular reference` no matter the number of maxDepth I set.
For instance I'm using:
`SerAny.serialize(Index, {
      maxDepth: 50,
    })`

**Comment by Judahh** [comment]
Does this package supports circular reference?

**Comment by terrymorse58** [comment]
Can you post the data that's revealing the error? I'd like to run some tests on it.

**Comment by Judahh** [comment]
The data is a bit complex to post it. But the full error is:
```
Error max depth of 20 levels exceeded, possible circular reference
(node:6053) Warning: Accessing non-existent property 'MongoError' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:667:11)
    at Object.get (internal/modules/cjs/loader.js:681:5)
    at Object.<anonymous> (/Users/judah/auth/node_modules/mongodb/lib/operations/operation.js:4:38)
    at Module._compile (internal/modules/cjs/loader.js:1075:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:1096:10)
    at Object.require.extensions.<computed> [as .js] (/Users/judah/auth/node_modules/ts-node/src/index.ts:1045:43)
    at Module.load (internal/modules/cjs/loader.js:940:32)
    at Function.Module._load (internal/modules/cjs/loader.js:781:14)
    at Module.require (internal/modules/cjs/loader.js:964:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/judah/auth/node_modules/mongodb/lib/operations/execute_operation.js:4:16)
    at Module._compile (internal/modules/cjs/loader.js:1075:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:1096:10)
    at Object.require.extensions.<computed> [as .js] (/Users/judah/auth/node_modules/ts-node/src/index.ts:1045:43)
    at Module.load (internal/modules/cjs/loader.js:940:32)
    at Function.Module._load (internal/modules/cjs/loader.js:781:14)
```

**Comment by terrymorse58** [comment]
I ran some tests and can confirm that _serialize-anything_ does not support circular references.

Here's the new test in test-suite.js. This is the result for _serialize-anything_:

```
Test27 (circular object reference):
  const src = { foo: "Foo", bar: {bar: "Bar"}};
  src.bar.baz = src;
    src:  <ref *1> { foo: 'Foo', bar: { bar: 'Bar', baz: [Circular *1] } }
*** TEST FAILED: Error maximum depth exceeded - possible circular reference
```

The other serializers also fail this test.

I will add circular reference support to the wish list.

**Comment by jric** [comment]
Please note that the latest version of serialize-anything does support circular references.
